// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_proto.proto

public final class ClientData {
  private ClientData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string pseudo = 2;</code>
     */
    boolean hasPseudo();
    /**
     * <code>optional string pseudo = 2;</code>
     */
    java.lang.String getPseudo();
    /**
     * <code>optional string pseudo = 2;</code>
     */
    com.google.protobuf.ByteString
        getPseudoBytes();

    /**
     * <code>optional .Data.Card card = 3;</code>
     */
    boolean hasCard();
    /**
     * <code>optional .Data.Card card = 3;</code>
     */
    ClientData.Data.Card getCard();
    /**
     * <code>optional .Data.Card card = 3;</code>
     */
    ClientData.Data.CardOrBuilder getCardOrBuilder();

    /**
     * <code>optional .Data.Bid bid = 4;</code>
     */
    boolean hasBid();
    /**
     * <code>optional .Data.Bid bid = 4;</code>
     */
    ClientData.Data.Bid getBid();
    /**
     * <code>optional .Data.Bid bid = 4;</code>
     */
    ClientData.Data.BidOrBuilder getBidOrBuilder();

    /**
     * <code>optional bool success = 5;</code>
     */
    boolean hasSuccess();
    /**
     * <code>optional bool success = 5;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Data)
      DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              pseudo_ = bs;
              break;
            }
            case 26: {
              ClientData.Data.Card.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = card_.toBuilder();
              }
              card_ = input.readMessage(ClientData.Data.Card.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(card_);
                card_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              ClientData.Data.Bid.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = bid_.toBuilder();
              }
              bid_ = input.readMessage(ClientData.Data.Bid.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bid_);
                bid_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientData.internal_static_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientData.internal_static_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientData.Data.class, ClientData.Data.Builder.class);
    }

    public static com.google.protobuf.Parser<Data> PARSER =
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Data.BidType}
     */
    public enum BidType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BID = 1;</code>
       */
      BID(0, 1),
      /**
       * <code>SKIP = 2;</code>
       */
      SKIP(1, 2),
      /**
       * <code>CAPOT = 3;</code>
       */
      CAPOT(2, 3),
      ;

      /**
       * <code>BID = 1;</code>
       */
      public static final int BID_VALUE = 1;
      /**
       * <code>SKIP = 2;</code>
       */
      public static final int SKIP_VALUE = 2;
      /**
       * <code>CAPOT = 3;</code>
       */
      public static final int CAPOT_VALUE = 3;


      public final int getNumber() { return value; }

      public static BidType valueOf(int value) {
        switch (value) {
          case 1: return BID;
          case 2: return SKIP;
          case 3: return CAPOT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BidType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BidType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BidType>() {
              public BidType findValueByNumber(int number) {
                return BidType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ClientData.Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final BidType[] VALUES = values();

      public static BidType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private BidType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Data.BidType)
    }

    /**
     * Protobuf enum {@code Data.CardType}
     */
    public enum CardType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SEVEN = 0;</code>
       */
      SEVEN(0, 0),
      /**
       * <code>EIGHT = 1;</code>
       */
      EIGHT(1, 1),
      /**
       * <code>NINE = 2;</code>
       */
      NINE(2, 2),
      /**
       * <code>TEN = 3;</code>
       */
      TEN(3, 3),
      /**
       * <code>JACK = 4;</code>
       */
      JACK(4, 4),
      /**
       * <code>QUEEN = 5;</code>
       */
      QUEEN(5, 5),
      /**
       * <code>KING = 6;</code>
       */
      KING(6, 6),
      /**
       * <code>ACE = 7;</code>
       */
      ACE(7, 7),
      ;

      /**
       * <code>SEVEN = 0;</code>
       */
      public static final int SEVEN_VALUE = 0;
      /**
       * <code>EIGHT = 1;</code>
       */
      public static final int EIGHT_VALUE = 1;
      /**
       * <code>NINE = 2;</code>
       */
      public static final int NINE_VALUE = 2;
      /**
       * <code>TEN = 3;</code>
       */
      public static final int TEN_VALUE = 3;
      /**
       * <code>JACK = 4;</code>
       */
      public static final int JACK_VALUE = 4;
      /**
       * <code>QUEEN = 5;</code>
       */
      public static final int QUEEN_VALUE = 5;
      /**
       * <code>KING = 6;</code>
       */
      public static final int KING_VALUE = 6;
      /**
       * <code>ACE = 7;</code>
       */
      public static final int ACE_VALUE = 7;


      public final int getNumber() { return value; }

      public static CardType valueOf(int value) {
        switch (value) {
          case 0: return SEVEN;
          case 1: return EIGHT;
          case 2: return NINE;
          case 3: return TEN;
          case 4: return JACK;
          case 5: return QUEEN;
          case 6: return KING;
          case 7: return ACE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CardType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CardType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CardType>() {
              public CardType findValueByNumber(int number) {
                return CardType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ClientData.Data.getDescriptor().getEnumTypes().get(1);
      }

      private static final CardType[] VALUES = values();

      public static CardType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CardType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Data.CardType)
    }

    /**
     * Protobuf enum {@code Data.CardColor}
     */
    public enum CardColor
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SPADES = 0;</code>
       */
      SPADES(0, 0),
      /**
       * <code>CLUBS = 1;</code>
       */
      CLUBS(1, 1),
      /**
       * <code>DIAMONDS = 2;</code>
       */
      DIAMONDS(2, 2),
      /**
       * <code>HEARTS = 3;</code>
       */
      HEARTS(3, 3),
      ;

      /**
       * <code>SPADES = 0;</code>
       */
      public static final int SPADES_VALUE = 0;
      /**
       * <code>CLUBS = 1;</code>
       */
      public static final int CLUBS_VALUE = 1;
      /**
       * <code>DIAMONDS = 2;</code>
       */
      public static final int DIAMONDS_VALUE = 2;
      /**
       * <code>HEARTS = 3;</code>
       */
      public static final int HEARTS_VALUE = 3;


      public final int getNumber() { return value; }

      public static CardColor valueOf(int value) {
        switch (value) {
          case 0: return SPADES;
          case 1: return CLUBS;
          case 2: return DIAMONDS;
          case 3: return HEARTS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CardColor>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CardColor>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CardColor>() {
              public CardColor findValueByNumber(int number) {
                return CardColor.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ClientData.Data.getDescriptor().getEnumTypes().get(2);
      }

      private static final CardColor[] VALUES = values();

      public static CardColor valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CardColor(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Data.CardColor)
    }

    public interface BidOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Data.Bid)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 bet = 1;</code>
       */
      boolean hasBet();
      /**
       * <code>optional int32 bet = 1;</code>
       */
      int getBet();

      /**
       * <code>required .Data.BidType type = 2;</code>
       */
      boolean hasType();
      /**
       * <code>required .Data.BidType type = 2;</code>
       */
      ClientData.Data.BidType getType();

      /**
       * <code>required .Data.CardColor trump = 3;</code>
       */
      boolean hasTrump();
      /**
       * <code>required .Data.CardColor trump = 3;</code>
       */
      ClientData.Data.CardColor getTrump();
    }
    /**
     * Protobuf type {@code Data.Bid}
     */
    public static final class Bid extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Data.Bid)
        BidOrBuilder {
      // Use Bid.newBuilder() to construct.
      private Bid(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Bid(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Bid defaultInstance;
      public static Bid getDefaultInstance() {
        return defaultInstance;
      }

      public Bid getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Bid(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                bet_ = input.readInt32();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                ClientData.Data.BidType value = ClientData.Data.BidType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
              case 24: {
                int rawValue = input.readEnum();
                ClientData.Data.CardColor value = ClientData.Data.CardColor.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                } else {
                  bitField0_ |= 0x00000004;
                  trump_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientData.internal_static_Data_Bid_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientData.internal_static_Data_Bid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientData.Data.Bid.class, ClientData.Data.Bid.Builder.class);
      }

      public static com.google.protobuf.Parser<Bid> PARSER =
          new com.google.protobuf.AbstractParser<Bid>() {
        public Bid parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Bid(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Bid> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int BET_FIELD_NUMBER = 1;
      private int bet_;
      /**
       * <code>optional int32 bet = 1;</code>
       */
      public boolean hasBet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 bet = 1;</code>
       */
      public int getBet() {
        return bet_;
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private ClientData.Data.BidType type_;
      /**
       * <code>required .Data.BidType type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Data.BidType type = 2;</code>
       */
      public ClientData.Data.BidType getType() {
        return type_;
      }

      public static final int TRUMP_FIELD_NUMBER = 3;
      private ClientData.Data.CardColor trump_;
      /**
       * <code>required .Data.CardColor trump = 3;</code>
       */
      public boolean hasTrump() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Data.CardColor trump = 3;</code>
       */
      public ClientData.Data.CardColor getTrump() {
        return trump_;
      }

      private void initFields() {
        bet_ = 0;
        type_ = ClientData.Data.BidType.BID;
        trump_ = ClientData.Data.CardColor.SPADES;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTrump()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, bet_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeEnum(3, trump_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, bet_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_.getNumber());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, trump_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static ClientData.Data.Bid parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ClientData.Data.Bid parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ClientData.Data.Bid parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ClientData.Data.Bid parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ClientData.Data.Bid parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ClientData.Data.Bid parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ClientData.Data.Bid parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ClientData.Data.Bid parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ClientData.Data.Bid parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ClientData.Data.Bid parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ClientData.Data.Bid prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Data.Bid}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Data.Bid)
          ClientData.Data.BidOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ClientData.internal_static_Data_Bid_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ClientData.internal_static_Data_Bid_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ClientData.Data.Bid.class, ClientData.Data.Bid.Builder.class);
        }

        // Construct using ClientData.Data.Bid.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          bet_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = ClientData.Data.BidType.BID;
          bitField0_ = (bitField0_ & ~0x00000002);
          trump_ = ClientData.Data.CardColor.SPADES;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ClientData.internal_static_Data_Bid_descriptor;
        }

        public ClientData.Data.Bid getDefaultInstanceForType() {
          return ClientData.Data.Bid.getDefaultInstance();
        }

        public ClientData.Data.Bid build() {
          ClientData.Data.Bid result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ClientData.Data.Bid buildPartial() {
          ClientData.Data.Bid result = new ClientData.Data.Bid(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.bet_ = bet_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.trump_ = trump_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ClientData.Data.Bid) {
            return mergeFrom((ClientData.Data.Bid)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ClientData.Data.Bid other) {
          if (other == ClientData.Data.Bid.getDefaultInstance()) return this;
          if (other.hasBet()) {
            setBet(other.getBet());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasTrump()) {
            setTrump(other.getTrump());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasTrump()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ClientData.Data.Bid parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ClientData.Data.Bid) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int bet_ ;
        /**
         * <code>optional int32 bet = 1;</code>
         */
        public boolean hasBet() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 bet = 1;</code>
         */
        public int getBet() {
          return bet_;
        }
        /**
         * <code>optional int32 bet = 1;</code>
         */
        public Builder setBet(int value) {
          bitField0_ |= 0x00000001;
          bet_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 bet = 1;</code>
         */
        public Builder clearBet() {
          bitField0_ = (bitField0_ & ~0x00000001);
          bet_ = 0;
          onChanged();
          return this;
        }

        private ClientData.Data.BidType type_ = ClientData.Data.BidType.BID;
        /**
         * <code>required .Data.BidType type = 2;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .Data.BidType type = 2;</code>
         */
        public ClientData.Data.BidType getType() {
          return type_;
        }
        /**
         * <code>required .Data.BidType type = 2;</code>
         */
        public Builder setType(ClientData.Data.BidType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .Data.BidType type = 2;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = ClientData.Data.BidType.BID;
          onChanged();
          return this;
        }

        private ClientData.Data.CardColor trump_ = ClientData.Data.CardColor.SPADES;
        /**
         * <code>required .Data.CardColor trump = 3;</code>
         */
        public boolean hasTrump() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required .Data.CardColor trump = 3;</code>
         */
        public ClientData.Data.CardColor getTrump() {
          return trump_;
        }
        /**
         * <code>required .Data.CardColor trump = 3;</code>
         */
        public Builder setTrump(ClientData.Data.CardColor value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          trump_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .Data.CardColor trump = 3;</code>
         */
        public Builder clearTrump() {
          bitField0_ = (bitField0_ & ~0x00000004);
          trump_ = ClientData.Data.CardColor.SPADES;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Data.Bid)
      }

      static {
        defaultInstance = new Bid(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Data.Bid)
    }

    public interface CardOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Data.Card)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .Data.CardType type = 1;</code>
       */
      boolean hasType();
      /**
       * <code>required .Data.CardType type = 1;</code>
       */
      ClientData.Data.CardType getType();

      /**
       * <code>required .Data.CardColor color = 2;</code>
       */
      boolean hasColor();
      /**
       * <code>required .Data.CardColor color = 2;</code>
       */
      ClientData.Data.CardColor getColor();
    }
    /**
     * Protobuf type {@code Data.Card}
     */
    public static final class Card extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Data.Card)
        CardOrBuilder {
      // Use Card.newBuilder() to construct.
      private Card(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Card(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Card defaultInstance;
      public static Card getDefaultInstance() {
        return defaultInstance;
      }

      public Card getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Card(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                ClientData.Data.CardType value = ClientData.Data.CardType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  type_ = value;
                }
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                ClientData.Data.CardColor value = ClientData.Data.CardColor.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  color_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientData.internal_static_Data_Card_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientData.internal_static_Data_Card_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientData.Data.Card.class, ClientData.Data.Card.Builder.class);
      }

      public static com.google.protobuf.Parser<Card> PARSER =
          new com.google.protobuf.AbstractParser<Card>() {
        public Card parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Card(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Card> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int TYPE_FIELD_NUMBER = 1;
      private ClientData.Data.CardType type_;
      /**
       * <code>required .Data.CardType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Data.CardType type = 1;</code>
       */
      public ClientData.Data.CardType getType() {
        return type_;
      }

      public static final int COLOR_FIELD_NUMBER = 2;
      private ClientData.Data.CardColor color_;
      /**
       * <code>required .Data.CardColor color = 2;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Data.CardColor color = 2;</code>
       */
      public ClientData.Data.CardColor getColor() {
        return color_;
      }

      private void initFields() {
        type_ = ClientData.Data.CardType.SEVEN;
        color_ = ClientData.Data.CardColor.SPADES;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasColor()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, color_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, color_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static ClientData.Data.Card parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ClientData.Data.Card parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ClientData.Data.Card parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ClientData.Data.Card parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ClientData.Data.Card parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ClientData.Data.Card parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ClientData.Data.Card parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ClientData.Data.Card parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ClientData.Data.Card parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ClientData.Data.Card parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ClientData.Data.Card prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Data.Card}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Data.Card)
          ClientData.Data.CardOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ClientData.internal_static_Data_Card_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ClientData.internal_static_Data_Card_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ClientData.Data.Card.class, ClientData.Data.Card.Builder.class);
        }

        // Construct using ClientData.Data.Card.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = ClientData.Data.CardType.SEVEN;
          bitField0_ = (bitField0_ & ~0x00000001);
          color_ = ClientData.Data.CardColor.SPADES;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ClientData.internal_static_Data_Card_descriptor;
        }

        public ClientData.Data.Card getDefaultInstanceForType() {
          return ClientData.Data.Card.getDefaultInstance();
        }

        public ClientData.Data.Card build() {
          ClientData.Data.Card result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ClientData.Data.Card buildPartial() {
          ClientData.Data.Card result = new ClientData.Data.Card(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.color_ = color_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ClientData.Data.Card) {
            return mergeFrom((ClientData.Data.Card)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ClientData.Data.Card other) {
          if (other == ClientData.Data.Card.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasColor()) {
            setColor(other.getColor());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasType()) {
            
            return false;
          }
          if (!hasColor()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ClientData.Data.Card parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ClientData.Data.Card) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private ClientData.Data.CardType type_ = ClientData.Data.CardType.SEVEN;
        /**
         * <code>required .Data.CardType type = 1;</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .Data.CardType type = 1;</code>
         */
        public ClientData.Data.CardType getType() {
          return type_;
        }
        /**
         * <code>required .Data.CardType type = 1;</code>
         */
        public Builder setType(ClientData.Data.CardType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .Data.CardType type = 1;</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = ClientData.Data.CardType.SEVEN;
          onChanged();
          return this;
        }

        private ClientData.Data.CardColor color_ = ClientData.Data.CardColor.SPADES;
        /**
         * <code>required .Data.CardColor color = 2;</code>
         */
        public boolean hasColor() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .Data.CardColor color = 2;</code>
         */
        public ClientData.Data.CardColor getColor() {
          return color_;
        }
        /**
         * <code>required .Data.CardColor color = 2;</code>
         */
        public Builder setColor(ClientData.Data.CardColor value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          color_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .Data.CardColor color = 2;</code>
         */
        public Builder clearColor() {
          bitField0_ = (bitField0_ & ~0x00000002);
          color_ = ClientData.Data.CardColor.SPADES;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Data.Card)
      }

      static {
        defaultInstance = new Card(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Data.Card)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PSEUDO_FIELD_NUMBER = 2;
    private java.lang.Object pseudo_;
    /**
     * <code>optional string pseudo = 2;</code>
     */
    public boolean hasPseudo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string pseudo = 2;</code>
     */
    public java.lang.String getPseudo() {
      java.lang.Object ref = pseudo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pseudo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pseudo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPseudoBytes() {
      java.lang.Object ref = pseudo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pseudo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARD_FIELD_NUMBER = 3;
    private ClientData.Data.Card card_;
    /**
     * <code>optional .Data.Card card = 3;</code>
     */
    public boolean hasCard() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Data.Card card = 3;</code>
     */
    public ClientData.Data.Card getCard() {
      return card_;
    }
    /**
     * <code>optional .Data.Card card = 3;</code>
     */
    public ClientData.Data.CardOrBuilder getCardOrBuilder() {
      return card_;
    }

    public static final int BID_FIELD_NUMBER = 4;
    private ClientData.Data.Bid bid_;
    /**
     * <code>optional .Data.Bid bid = 4;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Data.Bid bid = 4;</code>
     */
    public ClientData.Data.Bid getBid() {
      return bid_;
    }
    /**
     * <code>optional .Data.Bid bid = 4;</code>
     */
    public ClientData.Data.BidOrBuilder getBidOrBuilder() {
      return bid_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 5;
    private boolean success_;
    /**
     * <code>optional bool success = 5;</code>
     */
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool success = 5;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private void initFields() {
      id_ = 0;
      pseudo_ = "";
      card_ = ClientData.Data.Card.getDefaultInstance();
      bid_ = ClientData.Data.Bid.getDefaultInstance();
      success_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasCard()) {
        if (!getCard().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBid()) {
        if (!getBid().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPseudoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, card_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, bid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, success_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPseudoBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, card_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, bid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, success_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ClientData.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientData.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientData.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientData.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientData.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientData.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ClientData.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ClientData.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ClientData.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ClientData.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ClientData.Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Data)
        ClientData.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientData.internal_static_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientData.internal_static_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientData.Data.class, ClientData.Data.Builder.class);
      }

      // Construct using ClientData.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCardFieldBuilder();
          getBidFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pseudo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (cardBuilder_ == null) {
          card_ = ClientData.Data.Card.getDefaultInstance();
        } else {
          cardBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (bidBuilder_ == null) {
          bid_ = ClientData.Data.Bid.getDefaultInstance();
        } else {
          bidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        success_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientData.internal_static_Data_descriptor;
      }

      public ClientData.Data getDefaultInstanceForType() {
        return ClientData.Data.getDefaultInstance();
      }

      public ClientData.Data build() {
        ClientData.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ClientData.Data buildPartial() {
        ClientData.Data result = new ClientData.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pseudo_ = pseudo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (cardBuilder_ == null) {
          result.card_ = card_;
        } else {
          result.card_ = cardBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (bidBuilder_ == null) {
          result.bid_ = bid_;
        } else {
          result.bid_ = bidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.success_ = success_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientData.Data) {
          return mergeFrom((ClientData.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientData.Data other) {
        if (other == ClientData.Data.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPseudo()) {
          bitField0_ |= 0x00000002;
          pseudo_ = other.pseudo_;
          onChanged();
        }
        if (other.hasCard()) {
          mergeCard(other.getCard());
        }
        if (other.hasBid()) {
          mergeBid(other.getBid());
        }
        if (other.hasSuccess()) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (hasCard()) {
          if (!getCard().isInitialized()) {
            
            return false;
          }
        }
        if (hasBid()) {
          if (!getBid().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientData.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientData.Data) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object pseudo_ = "";
      /**
       * <code>optional string pseudo = 2;</code>
       */
      public boolean hasPseudo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string pseudo = 2;</code>
       */
      public java.lang.String getPseudo() {
        java.lang.Object ref = pseudo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pseudo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pseudo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPseudoBytes() {
        java.lang.Object ref = pseudo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pseudo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pseudo = 2;</code>
       */
      public Builder setPseudo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pseudo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pseudo = 2;</code>
       */
      public Builder clearPseudo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pseudo_ = getDefaultInstance().getPseudo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pseudo = 2;</code>
       */
      public Builder setPseudoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pseudo_ = value;
        onChanged();
        return this;
      }

      private ClientData.Data.Card card_ = ClientData.Data.Card.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ClientData.Data.Card, ClientData.Data.Card.Builder, ClientData.Data.CardOrBuilder> cardBuilder_;
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      public boolean hasCard() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      public ClientData.Data.Card getCard() {
        if (cardBuilder_ == null) {
          return card_;
        } else {
          return cardBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      public Builder setCard(ClientData.Data.Card value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          card_ = value;
          onChanged();
        } else {
          cardBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      public Builder setCard(
          ClientData.Data.Card.Builder builderForValue) {
        if (cardBuilder_ == null) {
          card_ = builderForValue.build();
          onChanged();
        } else {
          cardBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      public Builder mergeCard(ClientData.Data.Card value) {
        if (cardBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              card_ != ClientData.Data.Card.getDefaultInstance()) {
            card_ =
              ClientData.Data.Card.newBuilder(card_).mergeFrom(value).buildPartial();
          } else {
            card_ = value;
          }
          onChanged();
        } else {
          cardBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      public Builder clearCard() {
        if (cardBuilder_ == null) {
          card_ = ClientData.Data.Card.getDefaultInstance();
          onChanged();
        } else {
          cardBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      public ClientData.Data.Card.Builder getCardBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCardFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      public ClientData.Data.CardOrBuilder getCardOrBuilder() {
        if (cardBuilder_ != null) {
          return cardBuilder_.getMessageOrBuilder();
        } else {
          return card_;
        }
      }
      /**
       * <code>optional .Data.Card card = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ClientData.Data.Card, ClientData.Data.Card.Builder, ClientData.Data.CardOrBuilder> 
          getCardFieldBuilder() {
        if (cardBuilder_ == null) {
          cardBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ClientData.Data.Card, ClientData.Data.Card.Builder, ClientData.Data.CardOrBuilder>(
                  getCard(),
                  getParentForChildren(),
                  isClean());
          card_ = null;
        }
        return cardBuilder_;
      }

      private ClientData.Data.Bid bid_ = ClientData.Data.Bid.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ClientData.Data.Bid, ClientData.Data.Bid.Builder, ClientData.Data.BidOrBuilder> bidBuilder_;
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      public ClientData.Data.Bid getBid() {
        if (bidBuilder_ == null) {
          return bid_;
        } else {
          return bidBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      public Builder setBid(ClientData.Data.Bid value) {
        if (bidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bid_ = value;
          onChanged();
        } else {
          bidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      public Builder setBid(
          ClientData.Data.Bid.Builder builderForValue) {
        if (bidBuilder_ == null) {
          bid_ = builderForValue.build();
          onChanged();
        } else {
          bidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      public Builder mergeBid(ClientData.Data.Bid value) {
        if (bidBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              bid_ != ClientData.Data.Bid.getDefaultInstance()) {
            bid_ =
              ClientData.Data.Bid.newBuilder(bid_).mergeFrom(value).buildPartial();
          } else {
            bid_ = value;
          }
          onChanged();
        } else {
          bidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      public Builder clearBid() {
        if (bidBuilder_ == null) {
          bid_ = ClientData.Data.Bid.getDefaultInstance();
          onChanged();
        } else {
          bidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      public ClientData.Data.Bid.Builder getBidBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getBidFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      public ClientData.Data.BidOrBuilder getBidOrBuilder() {
        if (bidBuilder_ != null) {
          return bidBuilder_.getMessageOrBuilder();
        } else {
          return bid_;
        }
      }
      /**
       * <code>optional .Data.Bid bid = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ClientData.Data.Bid, ClientData.Data.Bid.Builder, ClientData.Data.BidOrBuilder> 
          getBidFieldBuilder() {
        if (bidBuilder_ == null) {
          bidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ClientData.Data.Bid, ClientData.Data.Bid.Builder, ClientData.Data.BidOrBuilder>(
                  getBid(),
                  getParentForChildren(),
                  isClean());
          bid_ = null;
        }
        return bidBuilder_;
      }

      private boolean success_ ;
      /**
       * <code>optional bool success = 5;</code>
       */
      public boolean hasSuccess() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool success = 5;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>optional bool success = 5;</code>
       */
      public Builder setSuccess(boolean value) {
        bitField0_ |= 0x00000010;
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool success = 5;</code>
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000010);
        success_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Data)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_Bid_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Data_Bid_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Data_Card_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Data_Card_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022client_proto.proto\"\300\003\n\004Data\022\n\n\002id\030\001 \002(" +
      "\005\022\016\n\006pseudo\030\002 \001(\t\022\030\n\004card\030\003 \001(\0132\n.Data.C" +
      "ard\022\026\n\003bid\030\004 \001(\0132\t.Data.Bid\022\017\n\007success\030\005" +
      " \001(\010\032O\n\003Bid\022\013\n\003bet\030\001 \001(\005\022\033\n\004type\030\002 \002(\0162\r" +
      ".Data.BidType\022\036\n\005trump\030\003 \002(\0162\017.Data.Card" +
      "Color\032D\n\004Card\022\034\n\004type\030\001 \002(\0162\016.Data.CardT" +
      "ype\022\036\n\005color\030\002 \002(\0162\017.Data.CardColor\"\'\n\007B" +
      "idType\022\007\n\003BID\020\001\022\010\n\004SKIP\020\002\022\t\n\005CAPOT\020\003\"[\n\010" +
      "CardType\022\t\n\005SEVEN\020\000\022\t\n\005EIGHT\020\001\022\010\n\004NINE\020\002" +
      "\022\007\n\003TEN\020\003\022\010\n\004JACK\020\004\022\t\n\005QUEEN\020\005\022\010\n\004KING\020\006",
      "\022\007\n\003ACE\020\007\"<\n\tCardColor\022\n\n\006SPADES\020\000\022\t\n\005CL" +
      "UBS\020\001\022\014\n\010DIAMONDS\020\002\022\n\n\006HEARTS\020\003B\014B\nClien" +
      "tData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Data_descriptor,
        new java.lang.String[] { "Id", "Pseudo", "Card", "Bid", "Success", });
    internal_static_Data_Bid_descriptor =
      internal_static_Data_descriptor.getNestedTypes().get(0);
    internal_static_Data_Bid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Data_Bid_descriptor,
        new java.lang.String[] { "Bet", "Type", "Trump", });
    internal_static_Data_Card_descriptor =
      internal_static_Data_descriptor.getNestedTypes().get(1);
    internal_static_Data_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Data_Card_descriptor,
        new java.lang.String[] { "Type", "Color", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
